package com.example.salonproject;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import java.util.HashMap;
import java.util.Map;

public class RegisterActivity extends AppCompatActivity {

    private EditText userFNameEditText;
    private EditText userLNameEditText;
    private EditText userPhoneEditText;
    private EditText userEmailEditText;
    private EditText userPwdEditText;
    private Button signupButton;

    private FirebaseAuth auth;
    DatabaseReference databaseRef;
    Map<String, Object> userhm;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_register_user);

        //Instantiate auth reference object
        auth = FirebaseAuth.getInstance();

        databaseRef = FirebaseDatabase.getInstance().getReference().child("Users"); //Reference to Users node

        //Get the view of resources
        userFNameEditText = (EditText) findViewById(R.id.userfname_edit_text);
        userLNameEditText = (EditText) findViewById(R.id.userlname_edit_text);
        userPhoneEditText = (EditText) findViewById(R.id.userphone_edit_text);
        userEmailEditText = (EditText) findViewById(R.id.useremail_edit_text);
        userPwdEditText = (EditText) findViewById(R.id.user_pwd_edit_text);

        //Get the view of signup_button
        signupButton = (Button) findViewById(R.id.signup_button);
        signupButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                //Adding data to Firebase database
                String userFName = userFNameEditText.getText().toString();
                String userLName = userLNameEditText.getText().toString();
                String userPhone = String.valueOf(userPhoneEditText.getText());
                String userEmail = userEmailEditText.getText().toString();
                String userPwd = userPwdEditText.getText().toString();

                if (TextUtils.isEmpty(userFName) || TextUtils.isEmpty(userLName) || TextUtils.isEmpty(userPhone) ||
                        TextUtils.isEmpty(userEmail) || TextUtils.isEmpty(userPwd)) {
                    Toast.makeText(RegisterActivity.this, "Empty Credential", Toast.LENGTH_SHORT).show();
                    return;
                } else if (userPwd.length() < 6) {
                    Toast.makeText(RegisterActivity.this, "Password too short", Toast.LENGTH_SHORT).show();
                    return;
                }

                //Register user with Firebase Authentication
                auth.createUserWithEmailAndPassword(userEmail, userPwd)
                        .addOnCompleteListener(RegisterActivity.this,
                                new OnCompleteListener<AuthResult>() {
                                    @Override
                                    public void onComplete(@NonNull Task<AuthResult> task) {
                                        if (task.isSuccessful()) {
                                            Toast.makeText(RegisterActivity.this, "Register is successful", Toast.LENGTH_SHORT).show();

                                            // Create a map to hold user data
                                            userhm = new HashMap<>();
                                            userhm.put("firstname", userFName);
                                            userhm.put("lastname", userLName);
                                            userhm.put("phone", userPhone);
                                            userhm.put("email", userEmail);

                                            // Get the user's unique ID generated by Firebase Authentication
                                            String userId = FirebaseAuth.getInstance().getCurrentUser().getUid();

                                            // Write user data to the database under "Users" node with the user's unique ID
                                            databaseRef.child(userId).setValue(userhm);

                                            // Redirect user to LoginActivity
                                            startActivity(new Intent(RegisterActivity.this, LoginActivity.class));
                                            finish(); //Close the current activity
                                        } else {
                                            Toast.makeText(RegisterActivity.this, "Register Failure", Toast.LENGTH_SHORT).show();
                                        }
                                    }
                                });
            }
        });
    }
}